"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'PT' | 'EN' | 'FR' | 'ES' | 'CN' | 'RU'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    flags: Record<Language, string>
    getFlag: (lang: Language) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
    PT: {
        // Header
        nav_home: "Início",
        nav_products: "Produtos",
        nav_my_orders: "Minhas Compras",
        btn_login: "Entrar",
        btn_register: "Começar",
        btn_sell: "Vender",
        btn_logout: "Sair",
        role_admin: "Administrador",
        role_vendor: "Vendedor",
        role_client: "Cliente",

        // Header Specific
        header_track: "Rastrear Pedido",
        header_welcome: "Olá",
        header_account: "Minha Conta",
        header_search: "O que você procura hoje?",
        header_depts: "Departamentos",
        header_deals: "Ofertas do Dia",
        header_suggestions: "Sugestões",
        header_search_for: "Buscar por",
        header_all_cats: "Ver todas",
        header_explore: "Explorar todo o catálogo",
        header_menu_cats: "Categorias",

        // Hero
        badge_platform: "A PLATAFORMA Nº1 DE ANGOLA",
        hero_title_1: "Venda em Angola,",
        hero_title_2: "Conquiste o Mundo.",
        hero_desc: "A solução completa para levar os seus produtos além-fronteiras. Pagamentos seguros, logística integrada e recebimentos em Kwanzas.",
        btn_buy: "Começar a Comprar",
        btn_become_vendor: "Tornar-se Vendedor",
        feature_secure_payments: "Pagamentos Seguros",
        feature_intl_shipping: "Envio Internacional",
        feature_vendor_count: "+1000 Vendedores",

        // Categories
        cat_title: "Explore por Categorias",
        cat_desc: "Encontre exatamente o que procura nas nossas categorias principais.",
        cat_electronics: "Eletrónicos",
        cat_fashion: "Moda",
        cat_home: "Casa & Decoração",
        cat_beauty: "Beleza",
        cat_sports: "Desporto",
        cat_toys: "Brinquedos",
        cat_books: "Livros",
        cat_food: "Alimentos",
        cat_others: "Outros",

        // Specific Departments
        cat_aplicativos_software: "Aplicativos & Software",

        cat_automotivo: "Automotivo",

        cat_beleza_saude: "Beleza & Saúde",

        cat_brinquedos_kids: "Brinquedos & Kids",

        cat_casa_decoracao: "Casa & Decoração",

        cat_esportes_lazer: "Esportes & Lazer",

        cat_livros_papelaria: "Livros & Papelaria",

        cat_moda_feminina: "Moda Feminina",
        cat_moda_masculina: "Moda Masculina",

        cat_prestacao_servico: "Prestação de Serviço",

        cat_supermercado: "Supermercado",

        cat_tecnologia_eletronica: "Tecnologia & Eletrónica",

        // Slug Aliases
        cat_tecnologia: "Tecnologia & Eletrónica",
        cat_esportes: "Esportes & Lazer",
        cat_brinquedos: "Brinquedos & Kids",
        cat_livros: "Livros & Papelaria",
        cat_prestacao_de_servico: "Prestação de Serviço",

        // ID Aliases (from categories.ts)
        cat_eletronicos: "Eletrónicos",
        cat_moda: "Moda",
        cat_beleza: "Beleza",
        cat_desporto: "Desporto",
        cat_alimentos: "Alimentos",
        cat_outros: "Outros",


        cat_subtitle: "Encontre o que você precisa em nossas seções especializadas",
        cat_view_all: "Ver Todas",

        // Trust Signals
        trust_delivery_title: "Receba em Casa",
        trust_delivery_desc: "Entrega em todo o país",
        trust_secure_title: "Compra Segura",
        trust_secure_desc: "Seus dados protegidos",
        trust_payment_title: "Pague como Quiser",
        trust_payment_desc: "Multicaixa, Transferência",
        trust_discount_title: "5% de Desconto",
        trust_discount_desc: "Pagamentos a pronto",

        // Value Props
        prop_global_title: "Alcance Global",
        prop_global_desc: "Não se limite. A nossa plataforma coloca os seus produtos à frente de clientes em todo o mundo.",
        prop_security_title: "Segurança Garantida",
        prop_security_desc: "Transações protegidas e verificação de vendedores para garantir a confiança em cada compra.",
        prop_growth_title: "Crescimento Rápido",
        prop_growth_desc: "Ferramentas de análise e gestão para ajudar o seu negócio a escalar.",

        // CTA
        cta_title: "Pronto para começar?",
        cta_desc: "Junte-se a milhares de empreendedores que já estão a transformar os seus negócios com a ProCommerceGlobal.",
        cta_btn: "Criar Conta Gratuita",

        // Cart
        cart_title: "Seu Carrinho",
        cart_empty: "Seu carrinho está vazio.",
        cart_continue: "Continuar Comprando",
        cart_subtotal: "Subtotal",
        cart_delivery_fee: "Taxa de Entrega",
        cart_total: "Total",
        cart_checkout: "Finalizar Compra",
        cart_delivery_method: "Método de Entrega",
        cart_delivery: "Entrega (Ao Domicílio)",
        cart_pickup: "Levantamento (Na Loja)",
        cart_free: "Grátis",
        cart_error_checkout: "Erro ao finalizar compra. Tente novamente.",
        cart_remove: "Remover",

        // Footer
        footer_slogan: "A plataforma líder de comércio eletrónico em Angola.",
        footer_platform: "Plataforma",
        footer_company: "Empresa",
        footer_legal: "Legal",
        footer_about: "Sobre Nós",
        footer_careers: "Carreiras",
        footer_contact: "Contactos",
        footer_terms: "Termos de Uso",
        footer_privacy: "Privacidade",
        footer_copyright: "ProCommerceGlobal. Feito com ❤️ em Angola.",
        // Featured
        featured_title: "Destaques da Semana",
        featured_desc: "Produtos selecionados com qualidade premium e os melhores preços.",
        btn_view_details: "Ver Detalhes",

        // Common Actions & Labels
        common_save: "Salvar",
        common_cancel: "Cancelar",
        common_edit: "Editar",
        common_delete: "Excluir",
        common_search: "Pesquisar",
        common_filter: "Filtrar",
        common_back: "Voltar",
        common_next: "Próximo",
        common_loading: "Carregando...",
        common_success: "Sucesso!",
        common_error: "Erro",
        common_actions: "Ações",
        common_status: "Estado",
        common_date: "Data",

        // Auth
        auth_email: "Endereço de Email",
        auth_password: "Palavra-passe",
        auth_name: "Nome Completo",
        auth_login_title: "Bem-vindo de volta",
        auth_register_title: "Crie a sua conta",
        auth_login_desc: "Entre com seu email e senha para aceder à sua conta.",
        auth_register_desc: "Preencha os dados abaixo para começar a usar a plataforma.",
        auth_forgot_password: "Esqueceu a palavra-passe?",
        auth_have_account: "Já tem uma conta? Entrar",
        auth_no_account: "Não tem conta? Registar",
        auth_no_account_hint: "Não tem conta?",
        auth_register_link: "Registar agora",
        auth_have_account_hint: "Já tem uma conta?",
        auth_login_link: "Entrar",
        auth_or: "OU",

        // Auth Missing Keys
        auth_term_customer: "Criar Conta Cliente",
        auth_term_vendor: "Tornar-se Vendedor",
        auth_desc_customer: "Junte-se a milhares de compradores e descubra o melhor de Angola.",
        auth_desc_vendor: "Comece a vender os seus produtos para milhões de clientes hoje mesmo.",
        auth_role_customer: "Sou Comprador",
        auth_role_vendor: "Sou Vendedor",
        auth_vendor_data_title: "Dados da Empresa/Vendedor",
        auth_vendor_data_desc: "Precisamos de alguns detalhes para verificar a sua conta comercial.",
        auth_doc_copy: "Cópia do Documento",
        auth_doc_hint: "Carregue uma foto clara ou PDF do seu documento.",
        auth_error_required: "Por favor, preencha todos os campos obrigatórios.",
        auth_error_password_match: "As palavras-passe não coincidem.",
        auth_error_password_length: "A palavra-passe deve ter pelo menos 6 caracteres.",

        // Products
        prod_add_to_cart: "Adicionar ao Carrinho",
        prod_buy_now: "Comprar Agora",
        prod_description: "Descrição",
        prod_specifications: "Especificações",
        prod_reviews: "Avaliações",
        prod_stock: "Em stock",
        prod_out_stock: "Esgotado",
        prod_sku: "REF",
        prod_category: "Categoria",
        prod_related: "Produtos Relacionados",
        prod_from_price: "A partir de",
        prod_check_offer: "Confira",
        prod_no_featured: "Ainda não temos produtos em destaque.",
        prod_no_highlight: "Nenhum produto em destaque no momento.",
        prod_sold_by: "Vendido por:",
        prod_units: "unidades",
        prod_unavailable: "Indisponível",
        prod_secure_transaction: "Transação segura e garantida pela ProCommerceGlobal",
        prod_default_category: "Geral",

        // Marketplace
        marketplace_title: "Marketplace ProCommerceGlobal",
        marketplace_subtitle: "Descubra produtos incríveis de empreendedores angolanos",
        marketplace_all_products: "Todos os Produtos",
        marketplace_no_products: "Nenhum produto encontrado",
        marketplace_no_products_desc: "Tente selecionar outra categoria ou volte mais tarde.",
        common_all: "Todos",

        // Checkout & Payment
        checkout_title: "Checkout Seguro",
        checkout_step_address: "Endereço de Entrega",
        checkout_step_payment: "Pagamento",
        checkout_method_title: "MÉTODO DE ENTREGA",
        checkout_method_delivery: "Entrega",
        checkout_method_pickup: "Levantamento",
        checkout_method_fee_calc: "+ Taxa Calculada",
        checkout_method_free: "Grátis",
        checkout_map_hint: "Localização da Entrega",
        checkout_map_desc: "Clique no mapa para marcar a localização.",
        checkout_addr_country: "País",
        checkout_addr_province: "Província",

        // Newsletter
        newsletter_title: "Fique por dentro das novidades",
        newsletter_desc: "Inscreva-se para receber ofertas exclusivas e atualizações.",
        newsletter_placeholder: "Seu melhor email",
        newsletter_sending: "Enviando...",
        newsletter_subscribe: "Subscrever",
        newsletter_app_download: "Baixe nosso App",
        checkout_addr_city: "Município / Cidade",
        checkout_addr_neighborhood: "Bairro",
        checkout_addr_street: "Rua / Avenida",
        checkout_addr_street_ph: "Nome da rua ou ponto de referência",
        checkout_addr_number: "Nº Casa / Apto",
        checkout_addr_number_ph: "Opcional",
        checkout_addr_phone: "Telefone",
        checkout_pickup_hint_title: "Instruções para Levantamento",
        checkout_pickup_hint_desc: "Dirija-se à loja do vendedor. Endereço nos detalhes do pedido.",
        checkout_btn_confirm: "Confirmar Endereço e Continuar",

        payment_currency: "Moeda de Pagamento",
        payment_method_manual: "Pagamento na Entrega",
        payment_method_card: "Visa / Mastercard",
        payment_method_crypto: "Binance Pay",
        payment_manual_desc: "Pague via Multicaixa ou Dinheiro ao receber.",
        payment_binance_title: "Gerar QR Code Binance",
        payment_btn_process: "Processando...",
        payment_btn_confirm: "Confirmar Pedido",
        payment_btn_pay_binance: "Pagar com Binance",

        summary_title: "Resumo do Pedido",
        summary_calculating: "Calculando...",
        summary_legal: "Ao confirmar, concorda com os Termos e Privacidade.",

        // Dashboard / Admin
        dash_overview: "Visão Geral",
        dash_products: "Meus Produtos",
        dash_orders: "Encomendas",
        dash_customers: "Clientes",
        dash_settings: "Configurações",
        dash_revenue: "Receita Total",
        dash_sales: "Vendas",
        dash_recent_orders: "Encomendas Recentes",
        dash_add_product: "Adicionar Produto",
        // Homepage
        home_popular_cats: "Categorias Populares",
        home_explore_news: "Explore as Novidades",
        home_desc_news: "Os melhores produtos de vendedores verificados, selecionados para você com garantia de qualidade.",
        home_full_catalog: "Explorar Catálogo Completo",
        home_first_seller: "Seja o primeiro a vender!",
        // Cart & Checkout
        cart_empty_title: "Seu carrinho está vazio",
        cart_empty_desc: "Que tal dar uma olhada nos nossos produtos?",
        cart_view_products: "Ver Produtos",
        cart_summary: "Resumo do Pedido",
        cart_clear: "Limpar Carrinho",

        // Common
        common_back_store: "Voltar para a Loja",
        footer_rights: "Todos os direitos reservados.",
        // Reviews
        reviews_title: "Avaliações dos Clientes",
        reviews_loading: "Carregando avaliações...",
        reviews_empty: "Este produto ainda não tem avaliações.",
        reviews_be_first: "Seja o primeiro a avaliar!",
        reviews_client: "Cliente",
        reviews_write: "Escreva uma avaliação",
        reviews_rating: "Sua Classificação",
        reviews_comment: "Seu Comentário",
        reviews_placeholder: "Conte o que achou do produto...",
        reviews_submit: "Enviar Avaliação",
        reviews_submitting: "Enviando...",
        reviews_login_req: "Você precisa estar logado para avaliar este produto.",
        reviews_login_btn: "Fazer Login",
        reviews_success: "Avaliação enviada com sucesso!",

        // Tracking
        track_title: "Rastrear Pedido",
        track_desc: "Digite o código de rastreio para ver o status.",
        track_label: "Código de Rastreio",
        track_btn: "Rastrear Agora",
        track_searching: "Buscando...",
        track_current_status: "Status Atual",
        track_via: "Via",
        track_destination: "Destino",
        track_forecast: "Previsão",
        track_days: "dias",
        track_history: "Histórico de Eventos",
        track_waiting: "Aguardando atualizações...",
        track_not_found: "Pedido não encontrado",
        track_error: "Erro ao buscar pedido",

        // Register
        reg_title: "Criar Nova Conta",
        reg_choose_role: "Escolha como deseja participar:",
        reg_customer: "Cliente",
        reg_vendor: "Vendedor",
        reg_continue: "Continuar para Cadastro",
        reg_origin_title: "Origem do Vendedor",
        reg_origin_national: "Nacional",
        reg_origin_intl: "Internacional",
        reg_doc_accepted: "Documento Aceite",
        reg_doc_accepted_plural: "Documentos Aceites",
        reg_data_account: "Dados da Conta",
        reg_data_personal: "Dados Pessoais & Documentos",
        reg_data_business: "Dados da Empresa / Loja",
        reg_personal_phone: "Telefone Pessoal",
        reg_birth_date: "Data de Nascimento",
        reg_address_personal: "Endereço Residencial",
        reg_doc_type: "Tipo de Documento",
        reg_doc_number: "Nº do Documento",
        reg_upload_title: "Fazer Upload",
        reg_doc_front_only: "Para Passaporte, envie apenas a página de dados pessoais (Frente).",
        reg_doc_both_sides: "Para este documento, é obrigatório enviar Frente e Verso.",
        reg_magic_title: "Use o celular para enviar as fotos",
        reg_magic_desc: "Aponte a câmera do seu telemóvel para o código acima.",
        reg_magic_connected: "Conectado",
        reg_magic_new_code: "Gerar Novo Código",
        reg_success_photos: "Fotos Recebidas com Sucesso!",
        reg_front: "FRENTE",
        reg_back_side: "VERSO",
        reg_store_name: "Nome da Loja",
        reg_nif: "NIF da Empresa",
        reg_email_biz: "Email Comercial",
        reg_phone_biz: "Telefone Comercial",
        reg_address_biz: "Endereço da Sede",
        reg_country_biz: "País da Sede Internacional",
        reg_btn_back: "Voltar",
        reg_btn_finish: "Finalizar Cadastro",
        reg_creating: "Criando Conta...",

        // Checkout Expanded
        checkout_coupon_title: "Possui um cupom?",
        checkout_coupon_placeholder: "Código do Cupom",
        checkout_coupon_apply: "Aplicar",
        checkout_coupon_validating: "Validando...",
        checkout_coupon_success: "Cupom aplicado!",
        checkout_coupon_invalid: "Cupom inválido",
        checkout_negotiable: "Sob Consulta",
        checkout_method_select: "Selecione o método",
        checkout_payment_select: "Selecione o pagamento",
        checkout_personal_data: "Seus Dados",
    },
    EN: {
        // Header
        nav_home: "Home",
        nav_products: "Products",
        nav_my_orders: "My Orders",
        btn_login: "Login",
        btn_register: "Get Started",
        btn_sell: "Sell",
        btn_logout: "Logout",
        role_admin: "Admin",
        role_vendor: "Vendor",
        role_client: "Customer",

        // Header Specific
        header_track: "Track Order",
        header_welcome: "Hello",
        header_account: "My Account",
        header_search: "What are you looking for?",
        header_depts: "Departments",
        header_deals: "Daily Deals",
        header_suggestions: "Suggestions",
        header_search_for: "Search for",
        header_all_cats: "See all",
        header_explore: "Explore full catalog",
        header_menu_cats: "Categories",

        // Hero
        badge_platform: "ANGOLA'S #1 PLATFORM",
        hero_title_1: "Sell in Angola,",
        hero_title_2: "Conquer the World.",
        hero_desc: "The complete solution to take your products across borders. Secure payments, integrated logistics, and payments in Kwanzas.",
        btn_buy: "Start Shopping",
        btn_become_vendor: "Become a Seller",
        feature_secure_payments: "Secure Payments",
        feature_intl_shipping: "Intl. Shipping",
        feature_vendor_count: "+1000 Sellers",

        // Categories
        cat_title: "Explore by Categories",
        cat_desc: "Find exactly what you are looking for in our main categories.",
        cat_electronics: "Electronics",
        cat_fashion: "Fashion",
        cat_home: "Home & Decor",
        cat_beauty: "Beauty",
        cat_sports: "Sports",
        cat_toys: "Toys",
        cat_books: "Books",
        cat_food: "Food",
        cat_others: "Others",

        // Specific Departments
        cat_aplicativos_software: "Apps & Software",
        cat_automotivo: "Automotive",
        cat_beleza_saude: "Beauty & Health",
        cat_brinquedos_kids: "Toys & Kids",
        cat_casa_decoracao: "Home & Decor",
        cat_esportes_lazer: "Sports & Leisure",
        cat_livros_papelaria: "Books & Stationery",
        cat_moda_feminina: "Women's Fashion",
        cat_moda_masculina: "Men's Fashion",
        cat_prestacao_servico: "Services",
        cat_supermercado: "Supermarket",
        cat_tecnologia_eletronica: "Tech & Electronics",

        // Slug Aliases
        cat_tecnologia: "Tech & Electronics",
        cat_esportes: "Sports & Leisure",
        cat_brinquedos: "Toys & Kids",
        cat_livros: "Books & Stationery",
        cat_prestacao_de_servico: "Services",

        // ID Aliases
        cat_eletronicos: "Electronics",
        cat_moda: "Fashion",
        cat_beleza: "Beauty",
        cat_desporto: "Sports",
        cat_alimentos: "Food",
        cat_outros: "Others",



        cat_subtitle: "Find exactly what you need in our main categories.",
        cat_view_all: "View All",

        // Trust Signals
        trust_delivery_title: "Home Delivery",
        trust_delivery_desc: "Nationwide delivery",
        trust_secure_title: "Secure Shopping",
        trust_secure_desc: "Your data is protected",
        trust_payment_title: "Pay Your Way",
        trust_payment_desc: "Multicaixa, Transfer",
        trust_discount_title: "5% Discount",
        trust_discount_desc: "On cash payments",

        // Value Props
        prop_global_title: "Global Reach",
        prop_global_desc: "Don't limit yourself. Our platform puts your products in front of customers worldwide.",
        prop_security_title: "Security Guaranteed",
        prop_security_desc: "Protected transactions and seller verification to ensure trust in every purchase.",
        prop_growth_title: "Rapid Growth",
        prop_growth_desc: "Analytics and management tools to help your business scale.",

        // CTA
        cta_title: "Ready to start?",
        cta_desc: "Join thousands of entrepreneurs who are already transforming their businesses with ProCommerceGlobal.",
        cta_btn: "Create Free Account",

        // Cart
        cart_title: "Your Cart",
        cart_empty: "Your cart is empty.",
        cart_continue: "Continue Shopping",
        cart_subtotal: "Subtotal",
        cart_delivery_fee: "Delivery Fee",
        cart_total: "Total",
        cart_checkout: "Checkout",
        cart_delivery_method: "Delivery Method",
        cart_delivery: "Delivery",
        cart_pickup: "Pickup",
        cart_remove: "Remove",

        // Footer
        footer_slogan: "Angola's leading e-commerce platform.",
        footer_platform: "Platform",
        footer_company: "Company",
        footer_legal: "Legal",
        footer_about: "About Us",
        footer_careers: "Careers",
        footer_contact: "Contacts",
        footer_terms: "Terms of Use",
        footer_privacy: "Privacy",
        footer_copyright: "ProCommerceGlobal. Made with ❤️ in Angola.",
        // Featured
        featured_title: "Week's Highlights",
        featured_desc: "Selected premium quality products at the best prices.",
        btn_view_details: "View Details",

        // Common Actions & Labels
        common_save: "Save",
        common_cancel: "Cancel",
        common_edit: "Edit",
        common_delete: "Delete",
        common_search: "Search",
        common_filter: "Filter",
        common_back: "Back",
        common_next: "Next",
        common_loading: "Loading...",
        common_success: "Success!",
        common_error: "Error",
        common_actions: "Actions",
        common_status: "Status",
        common_date: "Date",

        // Auth
        auth_email: "Email Address",
        auth_password: "Password",
        auth_name: "Full Name",
        auth_login_title: "Welcome back",
        auth_register_title: "Create your account",
        auth_login_desc: "Enter your email and password to access your account.",
        auth_register_desc: "Fill in the details below to start using the platform.",
        auth_forgot_password: "Forgot password?",
        auth_have_account: "Already have an account? Login",
        auth_no_account: "Don't have an account? Register",
        auth_no_account_hint: "Don't have an account?",
        auth_register_link: "Register now",
        auth_have_account_hint: "Already have an account?",
        auth_login_link: "Login",
        auth_or: "OR",

        // Auth Missing Keys
        auth_term_customer: "Create Customer Account",
        auth_term_vendor: "Become a Seller",
        auth_desc_customer: "Join thousands of shoppers and discover the best of Angola.",
        auth_desc_vendor: "Start selling your products to millions of customers today.",
        auth_role_customer: "I'm a Shopper",
        auth_role_vendor: "I'm a Seller",
        auth_vendor_data_title: "Business/Seller Data",
        auth_vendor_data_desc: "We need some details to verify your business account.",
        auth_doc_copy: "Document Copy",
        auth_doc_hint: "Upload a clear photo or PDF of your document.",
        auth_error_required: "Please fill in all required fields.",
        auth_error_password_match: "Passwords do not match.",
        auth_error_password_length: "Password must be at least 6 characters.",

        // Products
        prod_add_to_cart: "Add to Cart",
        prod_buy_now: "Buy Now",
        prod_description: "Description",
        prod_specifications: "Specifications",
        prod_reviews: "Reviews",
        prod_stock: "In Stock",
        prod_out_stock: "Out of Stock",
        prod_sku: "SKU",
        prod_category: "Category",
        prod_related: "Related Products",
        prod_from_price: "Starting at",
        prod_check_offer: "Check it out",
        prod_no_featured: "We don't have featured products yet.",
        prod_no_highlight: "No highlighted products at the moment.",
        prod_sold_by: "Sold by:",
        prod_units: "units",
        prod_unavailable: "Unavailable",
        prod_secure_transaction: "Secure transaction guaranteed by ProCommerceGlobal",
        prod_default_category: "General",

        // Marketplace
        marketplace_title: "ProCommerceGlobal Marketplace",
        marketplace_subtitle: "Discover amazing products from Angolan entrepreneurs",
        marketplace_all_products: "All Products",
        marketplace_no_products: "No products found",
        marketplace_no_products_desc: "Try selecting another category or check back later.",
        common_all: "All",

        // Checkout & Payment
        checkout_title: "Secure Checkout",
        checkout_step_address: "Delivery Address",
        checkout_step_payment: "Payment",
        checkout_method_title: "DELIVERY METHOD",
        checkout_method_delivery: "Delivery",
        checkout_method_pickup: "Pickup",
        checkout_method_fee_calc: "+ Calculated Fee",
        checkout_method_free: "Free",
        checkout_map_hint: "Delivery Location",
        checkout_map_desc: "Click on the map to mark the location.",
        checkout_addr_country: "Country",
        checkout_addr_province: "Province/State",

        // Newsletter
        newsletter_title: "Stay up to date",
        newsletter_desc: "Subscribe to receive exclusive offers and updates.",
        newsletter_placeholder: "Your best email",
        newsletter_sending: "Sending...",
        newsletter_subscribe: "Subscribe",
        newsletter_app_download: "Download our App",
        checkout_addr_street_ph: "Street name or landmark",
        checkout_addr_number: "Details / Apt",
        checkout_addr_number_ph: "Optional",
        checkout_addr_phone: "Phone",
        checkout_pickup_hint_title: "Pickup Instructions",
        checkout_pickup_hint_desc: "Go to the seller's store. Address in order details.",
        checkout_btn_confirm: "Confirm Address and Continue",

        payment_currency: "Payment Currency",
        payment_method_manual: "Pay on Delivery",
        payment_method_card: "Visa / Mastercard",
        payment_method_crypto: "Binance Pay",
        payment_manual_desc: "Pay via Cash or Card upon receipt.",
        payment_binance_title: "Generate Binance QR",
        payment_btn_process: "Processing...",
        payment_btn_confirm: "Confirm Order",
        payment_btn_pay_binance: "Pay with Binance",

        summary_title: "Order Summary",
        summary_calculating: "Calculating...",
        summary_legal: "By confirming, you agree to Terms and Privacy.",

        // Dashboard / Admin
        dash_overview: "Overview",
        dash_products: "My Products",
        dash_orders: "Orders",
        dash_customers: "Customers",
        dash_settings: "Settings",
        dash_revenue: "Total Revenue",
        dash_sales: "Sales",
        dash_recent_orders: "Recent Orders",
        dash_add_product: "Add Product",
        // Homepage
        home_popular_cats: "Popular Categories",
        home_explore_news: "Explore New Arrivals",
        home_desc_news: "Best products from verified sellers, selected for you with quality guarantee.",
        home_full_catalog: "Explore Full Catalog",
        home_first_seller: "Be the first to sell!",
        // Cart & Checkout
        cart_empty_title: "Your cart is empty",
        cart_empty_desc: "How about taking a look at our products?",
        cart_view_products: "View Products",
        cart_summary: "Order Summary",
        cart_clear: "Clear Cart",

        // Common
        common_back_store: "Back to Store",
        footer_rights: "All rights reserved.",
        // Reviews
        reviews_title: "Customer Reviews",
        reviews_loading: "Loading reviews...",
        reviews_empty: "This product has no reviews yet.",
        reviews_be_first: "Be the first to review!",
        reviews_client: "Customer",
        reviews_write: "Write a review",
        reviews_rating: "Your Rating",
        reviews_comment: "Your Comment",
        reviews_placeholder: "Tell us what you think...",
        reviews_submit: "Submit Review",
        reviews_submitting: "Submitting...",
        reviews_login_req: "You need to be logged in to review this product.",
        reviews_login_btn: "Login",
        reviews_success: "Review submitted successfully!",

        // Tracking
        track_title: "Track Order",
        track_desc: "Enter tracking code to see status.",
        track_label: "Tracking Code",
        track_btn: "Track Now",
        track_searching: "Searching...",
        track_current_status: "Current Status",
        track_via: "Via",
        track_destination: "Destination",
        track_forecast: "Forecast",
        track_days: "days",
        track_history: "Event History",
        track_waiting: "Waiting for updates...",
        track_not_found: "Order not found",
        track_error: "Error fetching order",

        // Register
        reg_title: "Create New Account",
        reg_choose_role: "Choose how you want to join:",
        reg_customer: "Customer",
        reg_vendor: "Vendor",
        reg_continue: "Continue to Registration",
        reg_origin_title: "Seller Origin",
        reg_origin_national: "National",
        reg_origin_intl: "International",
        reg_doc_accepted: "Accepted Document",
        reg_doc_accepted_plural: "Accepted Documents",
        reg_data_account: "Account Details",
        reg_data_personal: "Personal Data & Documents",
        reg_data_business: "Business / Store Data",
        reg_personal_phone: "Personal Phone",
        reg_birth_date: "Birth Date",
        reg_address_personal: "Home Address",
        reg_doc_type: "Document Type",
        reg_doc_number: "Document No.",
        reg_upload_title: "Upload",
        reg_doc_front_only: "For Passport, send only the personal data page (Front).",
        reg_doc_both_sides: "For this document, Front and Back are required.",
        reg_magic_title: "Use mobile to upload photos",
        reg_magic_desc: "Point your phone camera at the code above.",
        reg_magic_connected: "Connected",
        reg_magic_new_code: "Generate New Code",
        reg_success_photos: "Photos Received Successfully!",
        reg_front: "FRONT",
        reg_back_side: "BACK",
        reg_store_name: "Store Name",
        reg_nif: "Tax ID (NIF)",
        reg_email_biz: "Business Email",
        reg_phone_biz: "Business Phone",
        reg_address_biz: "HQ Address",
        reg_country_biz: "Intl. HQ Country",
        reg_btn_back: "Back",
        reg_btn_finish: "Finish Registration",
        reg_creating: "Creating Account...",

        // Checkout Expanded
        checkout_coupon_title: "Have a coupon?",
        checkout_coupon_placeholder: "Coupon Code",
        checkout_coupon_apply: "Apply",
        checkout_coupon_validating: "Validating...",
        checkout_coupon_success: "Coupon applied!",
        checkout_coupon_invalid: "Invalid coupon",
        checkout_negotiable: "Negotiable",
        checkout_method_select: "Select method",
        checkout_payment_select: "Select payment",
        checkout_personal_data: "Your Data",
    },
    FR: {
        // Header
        nav_home: "Accueil",
        nav_products: "Produits",
        nav_my_orders: "Mes Commandes",
        btn_login: "Connexion",
        btn_register: "Commencer",
        btn_sell: "Vendre",
        btn_logout: "Déconnexion",
        role_admin: "Administrateur",
        role_vendor: "Vendeur",
        role_client: "Client",

        // Header Specific
        header_track: "Suivre Commandes",
        header_welcome: "Bonjour",
        header_account: "Mon Compte",
        header_search: "Que cherchez-vous ?",
        header_depts: "Départements",
        header_deals: "Offres du Jour",
        header_suggestions: "Suggestions",
        header_search_for: "Rechercher",
        header_all_cats: "Voir tout",
        header_explore: "Explorer le catalogue",
        header_menu_cats: "Catégories",

        // Hero
        badge_platform: "LA PLATEFORME N°1 EN ANGOLA",
        hero_title_1: "Vendez en Angola,",
        hero_title_2: "Partez à la Conquête du Monde.",
        hero_desc: "La solution complète pour vos produits au-delà des frontières. Paiements sécurisés, logistique intégrée et paiements en Kwanzas.",
        btn_buy: "Commencer à Acheter",
        btn_become_vendor: "Devenir Vendeur",
        feature_secure_payments: "Paiements Sécurisés",
        feature_intl_shipping: "Expédition Intl.",
        feature_vendor_count: "+1000 Vendeurs",

        // Categories
        cat_title: "Explorer par Catégories",
        cat_desc: "Trouvez exactement ce que vous cherchez dans nos catégories principales.",
        cat_electronics: "Électronique",
        cat_fashion: "Mode",
        cat_home: "Maison & Déco",
        cat_beauty: "Beauté",
        cat_sports: "Sports",

        cat_toys: "Jouets",
        cat_books: "Livres",
        cat_food: "Aliments",
        cat_others: "Autres",
        // Specific Departments
        cat_aplicativos_software: "Applications & Logiciels",
        cat_automotivo: "Automobile",
        cat_beleza_saude: "Beauté & Santé",
        cat_brinquedos_kids: "Jouets & Enfants",
        cat_casa_decoracao: "Maison & Décoration",
        cat_esportes_lazer: "Sports & Loisirs",
        cat_livros_papelaria: "Livres & Papeterie",
        cat_moda_feminina: "Mode Femme",
        cat_moda_masculina: "Mode Homme",
        cat_prestacao_servico: "Services",
        cat_supermercado: "Supermarché",
        cat_tecnologia_eletronica: "Technologie & Électronique",

        // Slug Aliases
        cat_tecnologia: "Technologie & Électronique",
        cat_esportes: "Sports & Loisirs",
        cat_brinquedos: "Jouets & Enfants",
        cat_livros: "Livres & Papeterie",
        cat_prestacao_de_servico: "Services",

        // ID Aliases
        cat_eletronicos: "Électronique",
        cat_moda: "Mode",
        cat_beleza: "Beauté",
        cat_desporto: "Sports",
        cat_alimentos: "Alimentation",
        cat_outros: "Autres",



        cat_subtitle: "Trouvez exactement ce que vous cherchez.",
        cat_view_all: "Voir Tout",

        // Trust Signals
        trust_delivery_title: "Livraison à Domicile",
        trust_delivery_desc: "Livraison dans tout le pays",
        trust_secure_title: "Achat Sécurisé",
        trust_secure_desc: "Vos données protégées",
        trust_payment_title: "Payez comme vous voulez",
        trust_payment_desc: "Multicaixa, Virement",
        trust_discount_title: "5% de Réduction",
        trust_discount_desc: "Paiements comptant",

        // Value Props
        prop_global_title: "Portée Mondiale",
        prop_global_desc: "Ne vous limitez pas. Notre plateforme place vos produits devant des clients du monde entier.",
        prop_security_title: "Sécurité Garantie",
        prop_security_desc: "Transactions protégées et vérification des vendeurs pour garantir la confiance à chaque achat.",
        prop_growth_title: "Croissance Rapide",
        prop_growth_desc: "Outils d'analyse et de gestion pour aider votre entreprise à se développer.",

        // CTA
        cta_title: "Prêt à commencer ?",
        cta_desc: "Rejoignez des milliers d'entrepreneurs qui transforment déjà leurs entreprises avec ProCommerceGlobal.",
        cta_btn: "Créer un Compte Gratuit",

        // Cart
        cart_title: "Votre Panier",
        cart_empty: "Votre panier est vide.",
        cart_continue: "Continuer vos Achats",
        cart_subtotal: "Sous-total",
        cart_delivery_fee: "Frais de Livraison",
        cart_total: "Total",
        cart_checkout: "Payer",
        cart_delivery_method: "Méthode de Livraison",
        cart_delivery: "Livraison",
        cart_pickup: "Retrait",
        cart_remove: "Retirer",

        // Footer
        footer_slogan: "La principale plateforme de commerce électronique en Angola.",
        footer_platform: "Plateforme",
        footer_company: "Entreprise",
        footer_legal: "Légal",
        footer_about: "À Propos",
        footer_careers: "Carrières",
        footer_contact: "Contacts",
        footer_terms: "Conditions d'Utilisation",
        footer_privacy: "Confidentialité",
        footer_copyright: "ProCommerceGlobal. Fait avec ❤️ en Angola.",
        // Featured
        featured_title: "Points Forts",
        featured_desc: "Produits de qualité premium sélectionnés aux meilleurs prix.",
        btn_view_details: "Voir Détails",

        // Common Actions & Labels
        common_save: "Enregistrer",
        common_cancel: "Annuler",
        common_edit: "Modifier",
        common_delete: "Supprimer",
        common_search: "Rechercher",
        common_filter: "Filtrer",
        common_back: "Retour",
        common_next: "Suivant",
        common_loading: "Chargement...",
        common_success: "Succès !",
        common_error: "Erreur",
        common_actions: "Actions",
        common_status: "Statut",
        common_date: "Date",

        // Auth
        auth_email: "Adresse Email",
        auth_password: "Mot de passe",
        auth_name: "Nom Complet",
        auth_login_title: "Bienvenue",
        auth_register_title: "Créer un compte",
        auth_login_desc: "Entrez votre email et mot de passe pour accéder à votre compte.",
        auth_register_desc: "Remplissez les détails ci-dessous pour commencer.",
        auth_forgot_password: "Mot de passe oublié ?",
        auth_have_account: "Vous avez déjà un compte ? Connexion",
        auth_no_account: "Pas de compte ? S'inscrire",
        auth_no_account_hint: "Pas de compte ?",
        auth_register_link: "S'inscrire",
        auth_have_account_hint: "Vous avez déjà un compte ?",
        auth_login_link: "Connexion",
        auth_or: "OU",

        // Auth Missing Keys - FR
        auth_term_customer: "Compte Client",
        auth_term_vendor: "Devenir Vendeur",
        auth_desc_customer: "Rejoignez des milliers d'acheteurs.",
        auth_desc_vendor: "Commencez à vendre vos produits.",
        auth_role_customer: "Client",
        auth_role_vendor: "Vendeur",
        auth_vendor_data_title: "Données du Vendeur",
        auth_vendor_data_desc: "Détails pour la vérification.",
        auth_doc_copy: "Copie du Document",
        auth_doc_hint: "Téléchargez une photo claire ou PDF.",
        auth_error_required: "Champs obligatoires.",
        auth_error_password_match: "Les mots de passe ne correspondent pas.",
        auth_error_password_length: "6 caractères minimum.",

        // Products
        prod_add_to_cart: "Ajouter au Panier",
        prod_buy_now: "Acheter",
        prod_description: "Description",
        prod_specifications: "Spécifications",
        prod_reviews: "Avis",
        prod_stock: "En stock",
        prod_out_stock: "Épuisé",
        prod_sku: "REF",
        prod_category: "Catégorie",
        prod_related: "Produits Similaires",
        prod_from_price: "À partir de",
        prod_check_offer: "Voir l'offre",
        prod_no_featured: "Pas encore de produits en vedette.",
        prod_no_highlight: "Aucun produit mis en avant pour le moment.",
        prod_sold_by: "Vendu par :",
        prod_units: "unités",
        prod_unavailable: "Indisponible",
        prod_secure_transaction: "Transaction sécurisée et garantie par ProCommerceGlobal",
        prod_default_category: "Général",

        // Marketplace
        marketplace_title: "Marketplace ProCommerceGlobal",
        marketplace_subtitle: "Découvrez des produits incroyables d'entrepreneurs angolais",
        marketplace_all_products: "Tous les Produits",
        marketplace_no_products: "Aucun produit trouvé",
        marketplace_no_products_desc: "Essayez de sélectionner une autre catégorie ou revenez plus tard.",
        common_all: "Tous",

        // Checkout & Payment
        checkout_title: "Paiement Sécurisé",
        checkout_step_address: "Adresse de Livraison",
        checkout_step_payment: "Paiement",
        checkout_method_title: "MÉTHODE DE LIVRAISON",
        checkout_method_delivery: "Livraison",
        checkout_method_pickup: "Retrait",
        checkout_method_fee_calc: "+ Frais Calculés",
        checkout_method_free: "Gratuit",
        checkout_map_hint: "Lieu de Livraison",
        checkout_map_desc: "Cliquez sur la carte pour marquer l'emplacement.",
        checkout_addr_country: "Pays",
        checkout_addr_province: "Province",

        // Newsletter
        newsletter_title: "Restez informé",
        newsletter_desc: "Inscrivez-vous pour recevoir des offres exclusives et des mises à jour.",
        newsletter_placeholder: "Votre meilleur email",
        newsletter_sending: "Envoi...",
        newsletter_subscribe: "S'abonner",
        newsletter_app_download: "Télécharger notre application",
        checkout_addr_city: "Ville",
        checkout_addr_neighborhood: "Quartier",
        checkout_addr_street: "Rue / Avenue",
        checkout_addr_street_ph: "Nom de rue ou repère",
        checkout_addr_number: "Appartement / Détails",
        checkout_addr_number_ph: "Optionnel",
        checkout_addr_phone: "Téléphone",
        checkout_pickup_hint_title: "Instructions de Retrait",
        checkout_pickup_hint_desc: "Allez au magasin du vendeur. Adresse dans les détails.",
        checkout_btn_confirm: "Confirmer et Continuer",

        payment_currency: "Devise de Paiement",
        payment_method_manual: "Paiement à la Livraison",
        payment_method_card: "Visa / Mastercard",
        payment_method_crypto: "Binance Pay",
        payment_manual_desc: "Payez en espèces ou par carte à la réception.",
        payment_binance_title: "Générer QR Binance",
        payment_btn_process: "Traitement...",
        payment_btn_confirm: "Confirmer la Commande",
        payment_btn_pay_binance: "Payer avec Binance",

        summary_title: "Résumé de la Commande",
        summary_calculating: "Calcul...",
        summary_legal: "En confirmant, vous acceptez les Conditions et la Confidentialité.",

        // Dashboard / Admin
        dash_overview: "Vue d'ensemble",
        dash_products: "Mes Produits",
        dash_orders: "Commandes",
        dash_customers: "Clients",
        dash_settings: "Paramètres",
        dash_revenue: "Revenu Total",
        dash_sales: "Ventes",
        dash_recent_orders: "Commandes Récentes",
        dash_add_product: "Ajouter Produit",
        // Homepage
        home_popular_cats: "Catégories Populaires",
        home_explore_news: "Explorer les Nouveautés",
        home_desc_news: "Les meilleurs produits de vendeurs vérifiés, sélectionnés pour vous avec garantie de qualité.",
        home_full_catalog: "Explorer tout le catalogue",
        home_first_seller: "Soyez le premier à vendre !",
        // Cart & Checkout
        cart_empty_title: "Votre panier est vide",
        cart_empty_desc: "Que diriez-vous de jeter un coup d'œil à nos produits ?",
        cart_view_products: "Voir les produits",
        cart_summary: "Résumé de la commande",
        cart_clear: "Vider le panier",

        // Common
        common_back_store: "Retour à la boutique",
        footer_rights: "Tous droits réservés.",
        // Reviews
        reviews_title: "Avis des Clients",
        reviews_loading: "Chargement des avis...",
        reviews_empty: "Ce produit n'a pas encore d'avis.",
        reviews_be_first: "Soyez le premier à donner votre avis !",
        reviews_client: "Client",
        reviews_write: "Écrire un avis",
        reviews_rating: "Votre Note",
        reviews_comment: "Votre Commentaire",
        reviews_placeholder: "Dites-nous ce que vous en pensez...",
        reviews_submit: "Soumettre l'avis",
        reviews_submitting: "Envoi en cours...",
        reviews_login_req: "Vous devez être connecté pour évaluer ce produit.",
        reviews_login_btn: "Se connecter",
        reviews_success: "Avis soumis avec succès !",

        // Tracking
        track_title: "Suivre la Commande",
        track_desc: "Entrez le code de suivi pour voir le statut.",
        track_label: "Code de Suivi",
        track_btn: "Suivre Maintenant",
        track_searching: "Recherche...",
        track_current_status: "Statut Actuel",
        track_via: "Via",
        track_destination: "Destination",
        track_forecast: "Prévision",
        track_days: "jours",
        track_history: "Historique des Événements",
        track_waiting: "En attente de mises à jour...",
        track_not_found: "Commande non trouvée",
        track_error: "Erreur lors de la récupération",

        // Register
        reg_title: "Créer un Nouveau Compte",
        reg_choose_role: "Choisissez comment vous souhaitez rejoindre :",
        reg_customer: "Client",
        reg_vendor: "Vendeur",
        reg_continue: "Continuer l'inscription",
        reg_origin_title: "Origine du Vendeur",
        reg_origin_national: "National",
        reg_origin_intl: "International",
        reg_doc_accepted: "Document Accepté",
        reg_doc_accepted_plural: "Documents Acceptés",
        reg_data_account: "Détails du Compte",
        reg_data_personal: "Données Personnelles & Documents",
        reg_data_business: "Données Entreprise / Magasin",
        reg_personal_phone: "Téléphone Personnel",
        reg_birth_date: "Date de Naissance",
        reg_address_personal: "Adresse Domicile",
        reg_doc_type: "Type de Document",
        reg_doc_number: "N° de Document",
        reg_upload_title: "Télécharger",
        reg_doc_front_only: "Pour le Passeport, envoyez uniquement la page de données (Face).",
        reg_doc_both_sides: "Pour ce document, Recto et Verso sont requis.",
        reg_magic_title: "Utilisez le mobile pour envoyer les photos",
        reg_magic_desc: "Pointez la caméra de votre téléphone vers le code ci-dessus.",
        reg_magic_connected: "Connecté",
        reg_magic_new_code: "Générer un Nouveau Code",
        reg_success_photos: "Photos Reçues avec Succès !",
        reg_front: "RECTO",
        reg_back_side: "VERSO",
        reg_store_name: "Nom de la Boutique",
        reg_nif: "NIF Entreprise",
        reg_email_biz: "Email Professionnel",
        reg_phone_biz: "Téléphone Professionnel",
        reg_address_biz: "Adresse du Siège",
        reg_country_biz: "Pays du Siège Intl.",
        reg_btn_back: "Retour",
        reg_btn_finish: "Terminer l'Inscription",
        reg_creating: "Création du Compte...",

        // Checkout Expanded
        checkout_coupon_title: "Avez-vous un coupon ?",
        checkout_coupon_placeholder: "Code Coupon",
        checkout_coupon_apply: "Appliquer",
        checkout_coupon_validating: "Validation...",
        checkout_coupon_success: "Coupon appliqué !",
        checkout_coupon_invalid: "Coupon invalide",
        checkout_negotiable: "Négociable",
        checkout_method_select: "Sélectionner méthode",
        checkout_payment_select: "Sélectionner paiement",
        checkout_personal_data: "Vos Données",
    },
    ES: {
        // Reviews
        reviews_title: "Reseñas de Clientes",
        reviews_loading: "Cargando reseñas...",
        reviews_empty: "Este producto aún no tiene reseñas.",
        reviews_be_first: "¡Sé el primero en opinar!",
        reviews_client: "Cliente",
        reviews_write: "Escribe una reseña",
        reviews_rating: "Tu Calificación",
        reviews_comment: "Tu Comentario",
        reviews_placeholder: "Cuéntanos qué te pareció...",
        reviews_submit: "Enviar Reseña",
        reviews_submitting: "Enviando...",
        reviews_login_req: "Necesitas iniciar sesión para opinar.",
        reviews_login_btn: "Iniciar Sesión",
        reviews_success: "¡Reseña enviada con éxito!",
        // Header
        nav_home: "Inicio",
        nav_products: "Productos",
        nav_my_orders: "Mis Pedidos",
        btn_login: "Entrar",
        btn_register: "Empezar",
        btn_sell: "Vender",
        btn_logout: "Salir",
        role_admin: "Admin",
        role_vendor: "Vendedor",
        role_client: "Cliente",

        // Hero
        badge_platform: "LA PLATAFORMA Nº1 DE ANGOLA",
        hero_title_1: "Venda en Angola,",
        hero_title_2: "Conquiste el Mundo.",
        hero_desc: "La solución completa para llevar sus productos más allá de las fronteras. Pagos seguros, logística integrada y pagos en Kwanzas.",
        btn_buy: "Empezar a Comprar",
        btn_become_vendor: "Convertirse en Vendedor",
        feature_secure_payments: "Pagos Seguros",
        feature_intl_shipping: "Envío Internacional",
        feature_vendor_count: "+1000 Vendedores",

        // Categories
        cat_title: "Explorar por Categorías",
        cat_desc: "Encuentre exactamente lo que busca en nuestras categorías principales.",
        cat_electronics: "Electrónica",
        cat_fashion: "Moda",
        cat_home: "Hogar y Decoración",
        cat_beauty: "Belleza",
        cat_sports: "Deportes",

        cat_toys: "Juguetes",
        cat_books: "Libros",
        cat_food: "Alimentos",
        cat_others: "Otros",
        // Specific Departments
        cat_aplicativos_software: "Apps y Software",
        cat_automotivo: "Automotriz",
        cat_beleza_saude: "Belleza y Salud",
        cat_brinquedos_kids: "Juguetes y Niños",
        cat_casa_decoracao: "Hogar y Decoración",
        cat_esportes_lazer: "Deportes y Ocio",
        cat_livros_papelaria: "Libros y Papelería",
        cat_moda_feminina: "Moda Femenina",
        cat_moda_masculina: "Moda Masculina",
        cat_prestacao_servico: "Servicios",
        cat_supermercado: "Supermercado",
        cat_tecnologia_eletronica: "Tecnología y Electrónica",

        // Slug Aliases
        cat_tecnologia: "Tecnología y Electrónica",
        cat_esportes: "Deportes y Ocio",
        cat_brinquedos: "Juguetes y Niños",
        cat_livros: "Libros y Papelería",
        cat_prestacao_de_servico: "Servicios",

        // ID Aliases
        cat_eletronicos: "Electrónica",
        cat_moda: "Moda",
        cat_beleza: "Belleza",
        cat_desporto: "Deportes",
        cat_alimentos: "Alimentos",
        cat_outros: "Otros",



        cat_subtitle: "Encuentra exactamente lo que buscas.",
        cat_view_all: "Ver Todo",

        // Trust Signals
        trust_delivery_title: "Entrega a Domicilio",
        trust_delivery_desc: "En todo el país",
        trust_secure_title: "Compra Segura",
        trust_secure_desc: "Tus datos protegidos",
        trust_payment_title: "Paga como Quieras",
        trust_payment_desc: "Multicaixa, Transferencia",
        trust_discount_title: "5% de Descuento",
        trust_discount_desc: "Pagos al contado",

        // Value Props
        prop_global_title: "Alcance Global",
        prop_global_desc: "No se limite. Nuestra plataforma pone sus productos frente a clientes de todo el mundo.",
        prop_security_title: "Seguridad Garantizada",
        prop_security_desc: "Transacciones protegidas y verificación de vendedores para garantizar la confianza en cada compra.",
        prop_growth_title: "Crecimiento Rápido",
        prop_growth_desc: "Herramientas de análisis y gestión para ayudar a su negocio a escalar.",

        // CTA
        cta_title: "¿Listo para empezar?",
        cta_desc: "Únase a miles de emprendedores que ya están transformando sus negocios con ProCommerceGlobal.",
        cta_btn: "Crear Cuenta Gratuita",

        // Cart
        cart_title: "Tu Carrito",
        cart_empty: "Tu carrito está vacío.",
        cart_continue: "Seguir Comprando",
        cart_subtotal: "Subtotal",
        cart_delivery_fee: "Tarifa de Envío",
        cart_total: "Total",
        cart_checkout: "Finalizar Compra",
        cart_delivery_method: "Método de Entrega",
        cart_delivery: "Envío",
        cart_pickup: "Recogida",
        cart_remove: "Eliminar",

        // Footer
        footer_slogan: "La plataforma líder de comercio electrónico en Angola.",
        footer_platform: "Plataforma",
        footer_company: "Empresa",
        footer_legal: "Legal",
        footer_about: "Sobre Nosotros",
        footer_careers: "Carreras",
        footer_contact: "Contactos",
        footer_terms: "Términos de Uso",
        footer_privacy: "Privacidad",
        footer_copyright: "ProCommerceGlobal. Hecho con ❤️ en Angola.",
        // Featured
        featured_title: "Destacados",
        featured_desc: "Productos de calidad premium seleccionados a los mejores precios.",
        btn_view_details: "Ver Detalles",

        // Common Actions & Labels
        common_save: "Guardar",
        common_cancel: "Cancelar",
        common_edit: "Editar",
        common_delete: "Eliminar",
        common_search: "Buscar",
        common_filter: "Filtrar",
        common_back: "Volver",
        common_next: "Siguiente",
        common_loading: "Cargando...",
        common_success: "¡Éxito!",
        common_error: "Error",
        common_actions: "Acciones",
        common_status: "Estado",
        common_date: "Fecha",

        // Auth
        auth_email: "Correo Electrónico",
        auth_password: "Contraseña",
        auth_name: "Nombre Completo",
        auth_login_title: "Bienvenido de nuevo",
        auth_register_title: "Crea tu cuenta",
        auth_login_desc: "Ingresa tu correo y contraseña para acceder a tu cuenta.",
        auth_register_desc: "Completa los datos a continuación para comenzar.",
        auth_forgot_password: "¿Olvidaste la contraseña?",
        auth_have_account: "¿Ya tienes cuenta? Entrar",
        auth_no_account: "¿No tiene cuenta? Registrarse",
        auth_no_account_hint: "¿No tienes cuenta?",
        auth_register_link: "Registrarse",
        auth_have_account_hint: "¿Ya tienes una cuenta?",
        auth_login_link: "Iniciar Sesión",
        auth_or: "O",



        // Auth Missing Keys - ES
        auth_term_customer: "Crear Cuenta Cliente",
        auth_term_vendor: "Ser Vendedor",
        auth_desc_customer: "Únase a miles de compradores.",
        auth_desc_vendor: "Comience a vender sus productos.",
        auth_role_customer: "Comprador",
        auth_role_vendor: "Vendedor",
        auth_vendor_data_title: "Datos del Vendedor",
        auth_vendor_data_desc: "Detalles para verificación.",
        auth_doc_copy: "Copia del Documento",
        auth_doc_hint: "Suba una foto clara o PDF.",
        auth_error_required: "Campos obligatorios.",
        auth_error_password_match: "Las contraseñas no coinciden.",
        auth_error_password_length: "6 caracteres mínimo.",

        // Products
        prod_add_to_cart: "Añadir al Carrito",
        prod_buy_now: "Comprar Ahora",
        prod_description: "Descripción",
        prod_specifications: "Especificaciones",
        prod_reviews: "Reseñas",
        prod_stock: "En stock",
        prod_out_stock: "Agotado",
        prod_sku: "REF",
        prod_category: "Categoría",
        prod_related: "Productos Relacionados",
        prod_from_price: "Desde",
        prod_check_offer: "Ver oferta",
        prod_no_featured: "No hay productos destacados aún.",
        prod_no_highlight: "Ningún producto destacado por el momento.",
        prod_sold_by: "Vendido por:",
        prod_units: "unidades",
        prod_unavailable: "No disponible",
        prod_secure_transaction: "Transacción segura garantizada por ProCommerceGlobal",
        common_back_store: "Volver a la Tienda",
        prod_default_category: "General",

        // Marketplace
        marketplace_title: "Marketplace ProCommerceGlobal",
        marketplace_subtitle: "Descubra productos increíbles de emprendedores angoleños",
        marketplace_all_products: "Todos los Productos",
        marketplace_no_products: "No se encontraron productos",
        marketplace_no_products_desc: "Intente seleccionar otra categoría o vuelva más tarde.",
        common_all: "Todos",



        // Checkout
        checkout_title: "Finalizar Compra",
        checkout_step_address: "Dirección de Entrega",
        checkout_step_payment: "Pago",
        checkout_method_title: "MÉTODO DE ENTREGA",
        checkout_method_delivery: "Envío",
        checkout_method_pickup: "Recogida",
        checkout_method_fee_calc: "+ Tarifa Calculada",
        checkout_method_free: "Gratis",
        checkout_map_hint: "Ubicación de Entrega",
        checkout_map_desc: "Haga clic en el mapa para marcar la ubicación.",
        checkout_addr_country: "País",
        checkout_addr_province: "Provincia",

        // Newsletter
        newsletter_title: "Mantente informado",
        newsletter_desc: "Suscríbete para recibir ofertas exclusivas y actualizaciones.",
        newsletter_placeholder: "Tu mejor correo",
        newsletter_sending: "Enviando...",
        newsletter_subscribe: "Suscribirse",
        newsletter_app_download: "Descarga nuestra App",
        checkout_addr_city: "Ciudad",
        checkout_addr_neighborhood: "Barrio",
        checkout_addr_street: "Calle / Avenida",
        checkout_addr_street_ph: "Nombre de calle o referencia",
        checkout_addr_number: "Nº Casa / Apto",
        checkout_addr_number_ph: "Opcional",
        checkout_addr_phone: "Teléfono",
        checkout_pickup_hint_title: "Instrucciones de Recogida",
        checkout_pickup_hint_desc: "Vaya a la tienda del vendedor. Dirección en detalles.",
        checkout_btn_confirm: "Confirmar Dirección y Continuar",

        payment_currency: "Moneda de Pago",
        payment_method_manual: "Pago contra Reembolso",
        payment_method_card: "Visa / Mastercard",
        payment_method_crypto: "Binance Pay",
        payment_manual_desc: "Pague en efectivo o tarjeta al recibir.",
        payment_binance_title: "Generar QR Binance",
        payment_btn_process: "Procesando...",
        payment_btn_confirm: "Confirmar Pedido",
        payment_btn_pay_binance: "Pagar con Binance",

        summary_title: "Resumen del Pedido",
        summary_calculating: "Calculando...",
        summary_legal: "Al confirmar, acepta los Términos y Privacidad.",

        // Dashboard / Admin
        dash_overview: "Resumen",
        dash_products: "Mis Productos",
        dash_orders: "Pedidos",
        dash_customers: "Clientes",
        dash_settings: "Ajustes",
        dash_revenue: "Ingresos Totales",
        dash_sales: "Ventas",
        dash_recent_orders: "Pedidos Recientes",
        dash_add_product: "Añadir Producto",
        // Cart & Checkout
        cart_empty_title: "Tu carrito está vacío",
        cart_empty_desc: "¿Qué tal si echas un vistazo a nuestros productos?",
        cart_view_products: "Ver Productos",
        cart_summary: "Resumen del Pedido",
        cart_clear: "Vaciar Carrito",

        // Common
        common_back_store: "Volver a la Tienda",
        footer_rights: "Todos los derechos reservados.",

        // Tracking
        track_title: "Rastrear Pedido",
        track_desc: "Ingresa el código de rastreo para ver el estado.",
        track_label: "Código de Rastreo",
        track_btn: "Rastrear Ahora",
        track_searching: "Buscando...",
        track_current_status: "Estado Actual",
        track_via: "Vía",
        track_destination: "Destino",
        track_forecast: "Pronóstico",
        track_days: "días",
        track_history: "Historial de Eventos",
        track_waiting: "Esperando actualizaciones...",
        track_not_found: "Pedido no encontrado",
        track_error: "Error al buscar pedido",

        // Register
        reg_title: "Crear Nueva Cuenta",
        reg_choose_role: "Elige cómo deseas unirte:",
        reg_customer: "Cliente",
        reg_vendor: "Vendedor",
        reg_continue: "Continuar al Registro",
        reg_origin_title: "Origen del Vendedor",
        reg_origin_national: "Nacional",
        reg_origin_intl: "Internacional",
        reg_doc_accepted: "Documento Aceptado",
        reg_doc_accepted_plural: "Documentos Aceptados",
        reg_data_account: "Detalles de la Cuenta",
        reg_data_personal: "Datos Personales y Documentos",
        reg_data_business: "Datos de la Empresa / Tienda",
        reg_personal_phone: "Teléfono Personal",
        reg_birth_date: "Fecha de Nacimiento",
        reg_address_personal: "Dirección Domiciliaria",
        reg_doc_type: "Tipo de Documento",
        reg_doc_number: "Nº de Documento",
        reg_upload_title: "Subir",
        reg_doc_front_only: "Para Pasaporte, envía solo la página de datos (Frente).",
        reg_doc_both_sides: "Para este documento, se requiere Frente y Dorso.",
        reg_magic_title: "Usa el móvil para subir fotos",
        reg_magic_desc: "Apunta la cámara de tu teléfono al código de arriba.",
        reg_magic_connected: "Conectado",
        reg_magic_new_code: "Generar Nuevo Código",
        reg_success_photos: "¡Fotos Recibidas con Éxito!",
        reg_front: "FRENTE",
        reg_back_side: "DORSO",
        reg_store_name: "Nombre de la Tienda",
        reg_nif: "NIF Empresa",
        reg_email_biz: "Email Comercial",
        reg_phone_biz: "Teléfono Comercial",
        reg_address_biz: "Dirección de Sede",
        reg_country_biz: "País Sede Intl.",
        reg_btn_back: "Volver",
        reg_btn_finish: "Finalizar Registro",
        reg_creating: "Creando Cuenta...",

        // Checkout Expanded
        checkout_coupon_title: "¿Tienes un cupón?",
        checkout_coupon_placeholder: "Código del Cupón",
        checkout_coupon_apply: "Aplicar",
        checkout_coupon_validating: "Validando...",
        checkout_coupon_success: "¡Cupón aplicado!",
        checkout_coupon_invalid: "Cupón inválido",
        checkout_negotiable: "Negociable",
        checkout_method_select: "Seleccionar método",
        checkout_payment_select: "Seleccionar pago",
        checkout_personal_data: "Tus Datos",

    },

    RU: {
        // Header
        nav_home: "Главная",
        nav_products: "Товары",
        nav_my_orders: "Мои заказы",
        btn_login: "Войти",
        btn_register: "Начать",
        btn_sell: "Продать",
        btn_logout: "Выйти",
        role_admin: "Администратор",
        role_vendor: "Продавец",
        role_client: "Клиент",

        // Header Specific
        header_track: "Отследить заказ",
        header_welcome: "Привет",
        header_account: "Мой аккаунт",
        header_search: "Что вы ищете?",
        header_depts: "Отделы",
        header_deals: "Предложения дня",
        header_suggestions: "Предложения",
        header_search_for: "Искать",
        header_all_cats: "Посмотреть все",
        header_explore: "Весь каталог",
        header_menu_cats: "Категории",

        // Hero
        badge_platform: "ПЛАТФОРМА №1 В АНГОЛЕ",
        hero_title_1: "Продавайте в Анголе,",
        hero_title_2: "Завоюйте мир.",
        hero_desc: "Полное решение для вывода ваших товаров за границу. Безопасные платежи, интегрированная логистика и выплаты в кванзах.",
        btn_buy: "Начать покупки",
        btn_become_vendor: "Стать продавцом",
        feature_secure_payments: "Безопасные платежи",
        feature_intl_shipping: "Междун. доставка",
        feature_vendor_count: "+1000 Продавцов",

        // Auth
        auth_email: "Электронная почта",
        auth_password: "Пароль",
        auth_name: "Полное имя",
        auth_login_title: "С возвращением",
        auth_register_title: "Создайте аккаунт",
        auth_login_desc: "Введите email и пароль для входа.",
        auth_register_desc: "Заполните данные ниже, чтобы начать.",
        auth_forgot_password: "Забыли пароль?",
        auth_have_account: "Есть аккаунт? Войти",
        auth_no_account: "Нет аккаунта? Регистрация",
        auth_no_account_hint: "Нет аккаунта?",
        auth_register_link: "Зарегистрироваться",
        auth_have_account_hint: "Уже есть аккаунт?",
        auth_login_link: "Войти",
        auth_or: "ИЛИ",

        // Categories
        cat_title: "Поиск по категориям",
        cat_desc: "Найдите именно то, что ищете, в наших основных категориях.",
        cat_electronics: "Электроника",
        cat_fashion: "Мода",
        cat_home: "Дом и декор",
        cat_beauty: "Красота",
        cat_sports: "Спорт",
        cat_toys: "Игрушки",
        cat_books: "Книги",
        cat_food: "Еда",
        cat_others: "Другое",
        // Specific Departments
        cat_aplicativos_software: "Приложения и ПО",
        cat_automotivo: "Автомобили",
        cat_beleza_saude: "Красота и Здоровье",
        cat_brinquedos_kids: "Игрушки и Дети",
        cat_casa_decoracao: "Дом и Декор",
        cat_esportes_lazer: "Спорт и Отдых",
        cat_livros_papelaria: "Книги и Канцелярия",
        cat_moda_feminina: "Женская Мода",
        cat_moda_masculina: "Мужская Мода",
        cat_prestacao_servico: "Услуги",
        cat_supermercado: "Супермаркет",
        cat_tecnologia_eletronica: "Технологии и Электроника",

        // Slug Aliases
        cat_tecnologia: "Технологии и Электроника",
        cat_esportes: "Спорт и Отдых",
        cat_brinquedos: "Игрушки и Дети",
        cat_livros: "Книги и Канцелярия",
        cat_prestacao_de_servico: "Услуги",

        // ID Aliases
        cat_eletronicos: "Электроника",
        cat_moda: "Мода",
        cat_beleza: "Красота",
        cat_desporto: "Спорт",
        cat_alimentos: "Еда",
        cat_outros: "Другое",




        // Value Props
        prop_global_title: "Глобальный охват",
        prop_global_desc: "Не ограничивайте себя. Наша платформа представляет ваши товары клиентам по всему миру.",
        prop_security_title: "Гарантия безопасности",
        prop_security_desc: "Защищенные транзакции и проверка продавцов для обеспечения доверия к каждой покупке.",
        prop_growth_title: "Быстрый рост",
        prop_growth_desc: "Инструменты аналитики и управления для масштабирования вашего бизнеса.",

        // CTA
        cta_title: "Готовы начать?",
        cta_desc: "Присоединяйтесь к тысячам предпринимателей, которые уже трансформируют свой бизнес с ProCommerceGlobal.",
        cta_btn: "Создать бесплатный аккаунт",

        // Cart
        cart_title: "Ваша корзина",
        cart_empty: "Ваша корзина пуста.",
        cart_continue: "Продолжить покупки",
        cart_subtotal: "Подытог",
        cart_delivery_fee: "Стоимость доставки",
        cart_total: "Итого",
        cart_checkout: "Оформить заказ",
        cart_delivery_method: "Способ доставки",
        cart_delivery: "Доставка",

        // Newsletter
        newsletter_title: "Будьте в курсе",
        newsletter_desc: "Подпишитесь на эксклюзивные предложения и новости.",
        newsletter_placeholder: "Ваш лучший email",
        newsletter_sending: "Отправка...",
        newsletter_subscribe: "Подписаться",
        newsletter_app_download: "Скачать приложение",
        cart_pickup: "Самовывоз",
        cart_remove: "Удалить",

        // Footer
        footer_slogan: "Ведущая платформа электронной коммерции в Анголе.",
        footer_platform: "Платформа",
        footer_company: "Компания",
        footer_legal: "Право",
        footer_about: "О нас",
        footer_careers: "Вакансии",
        footer_contact: "Контакты",
        footer_terms: "Условия использования",
        footer_privacy: "Конфиденциальность",
        footer_copyright: "ProCommerceGlobal. Сделано с ❤️ в Анголе.",
        // Featured
        featured_title: "Лучшее за неделю",
        featured_desc: "Избранные товары премиум-класса по лучшим ценам.",
        btn_view_details: "Просмотр деталей",
        prod_sold_by: "Продавец:",
        prod_units: "единиц",
        prod_unavailable: "Недоступно",
        prod_secure_transaction: "Безопасная транзакция, гарантированная ProCommerceGlobal",
        prod_default_category: "Общее",

        // Marketplace
        marketplace_title: "Маркетплейс ProCommerceGlobal",
        marketplace_subtitle: "Откройте для себя удивительные товары от ангольских предпринимателей",
        marketplace_all_products: "Все товары",
        marketplace_no_products: "Товары не найдены",
        marketplace_no_products_desc: "Попробуйте выбрать другую категорию или зайдите позже.",
        common_all: "Все",
        // Homepage
        home_popular_cats: "Популярные Категории",
        home_explore_news: "Изучите Новинки",
        home_desc_news: "Лучшие товары от проверенных продавцов, отобранные для вас с гарантией качества.",
        home_full_catalog: "Весь Каталог",
        home_first_seller: "Станьте первым продавцом!",
        // Cart & Checkout
        cart_empty_title: "Ваша корзина пуста",
        cart_empty_desc: "Как насчет того, чтобы взглянуть на наши товары?",
        cart_view_products: "Посмотреть товары",
        cart_summary: "Сводка заказа",
        cart_clear: "Очистить корзину",

        // Common
        common_back_store: "Вернуться в магазин",
        footer_rights: "Все права защищены.",
        // Reviews
        reviews_title: "Отзывы клиентов",
        reviews_loading: "Загрузка отзывов...",
        reviews_empty: "У этого товара пока нет отзывов.",
        reviews_be_first: "Будьте первым, кто оставит отзыв!",
        reviews_client: "Клиент",
        reviews_write: "Написать отзыв",
        reviews_rating: "Ваша оценка",
        reviews_comment: "Ваш комментарий",
        reviews_placeholder: "Расскажите нам, что вы думаете...",
        reviews_submit: "Отправить отзыв",
        reviews_submitting: "Отправка...",
        reviews_login_req: "Вам нужно войти, чтобы оставить отзыв.",
        reviews_login_btn: "Войти",
        reviews_success: "Отзыв успешно отправлен!",

        // Tracking
        track_title: "Отследить заказ",
        track_desc: "Введите код отслеживания, чтобы увидеть статус.",
        track_label: "Код отслеживания",
        track_btn: "Отследить",
        track_searching: "Поиск...",
        track_current_status: "Текущий статус",
        track_via: "Через",
        track_destination: "Назначение",
        track_forecast: "Прогноз",
        track_days: "дней",
        track_history: "История событий",
        track_waiting: "Ожидание обновлений...",
        track_not_found: "Заказ не найден",
        track_error: "Ошибка поиска",

        // Register
        reg_title: "Создать учетную запись",
        reg_choose_role: "Выберите роль:",
        reg_customer: "Клиент",
        reg_vendor: "Продавец",
        reg_continue: "Продолжить регистрацию",
        reg_origin_title: "Происхождение продавца",
        reg_origin_national: "Национальный",
        reg_origin_intl: "Международный",
        reg_doc_accepted: "Принимаемый документ",
        reg_doc_accepted_plural: "Принимаемые документы",
        reg_data_account: "Данные аккаунта",
        reg_data_personal: "Личные данные и документы",
        reg_data_business: "Данные бизнеса / магазина",
        reg_personal_phone: "Личный телефон",
        reg_birth_date: "Дата рождения",
        reg_address_personal: "Домашний адрес",
        reg_doc_type: "Тип документа",
        reg_doc_number: "Номер документа",
        reg_upload_title: "Загрузить",
        reg_doc_front_only: "Для паспорта отправьте только страницу с данными (Лицевая).",
        reg_doc_both_sides: "Для этого документа требуются обе стороны.",
        reg_magic_title: "Используйте телефон для загрузки фото",
        reg_magic_desc: "Наведите камеру телефона на код выше.",
        reg_magic_connected: "Подключено",
        reg_magic_new_code: "Сгенерировать новый код",
        reg_success_photos: "Фото успешно получены!",
        reg_front: "ЛИЦЕВАЯ",
        reg_back_side: "ОБОРОТНАЯ",
        reg_store_name: "Название магазина",
        reg_nif: "ИНН",
        reg_email_biz: "Рабочий Email",
        reg_phone_biz: "Рабочий телефон",
        reg_address_biz: "Адрес штаб-квартиры",
        reg_country_biz: "Страна штаб-квартиры",
        reg_btn_back: "Назад",
        reg_btn_finish: "Завершить регистрацию",
        reg_creating: "Создание аккаунта...",

        // Checkout Expanded
        checkout_coupon_title: "Есть купон?",
        checkout_coupon_placeholder: "Код купона",
        checkout_coupon_apply: "Применить",
        checkout_coupon_validating: "Проверка...",
        checkout_coupon_success: "Купон применен!",
        checkout_coupon_invalid: "Неверный купон",
        checkout_negotiable: "Договорная",
        checkout_method_select: "Выберите метод",
        checkout_payment_select: "Выберите оплату",
        checkout_personal_data: "Ваши данные",
    },
    CN: {
        // Header
        nav_home: "首页",
        nav_products: "产品",
        nav_my_orders: "我的订单",
        btn_login: "登录",
        btn_register: "开始",
        btn_sell: "销售",
        btn_logout: "退出",
        role_admin: "管理员",
        role_vendor: "卖家",
        role_client: "客户",

        // Header Specific
        header_track: "追踪订单",
        header_welcome: "你好",
        header_account: "我的账户",
        header_search: "您在找什么？",
        header_depts: "部门",
        header_deals: "每日特惠",
        header_suggestions: "建议",
        header_search_for: "搜索",
        header_all_cats: "查看全部",
        header_explore: "浏览完整目录",
        header_menu_cats: "分类",

        // Homepage
        home_popular_cats: "热门分类",
        home_explore_news: "探索新品",
        home_desc_news: "来自认证卖家的最佳产品，为您精选，质量保证。",
        home_full_catalog: "浏览完整目录",
        home_first_seller: "成为第一个卖家！",

        // Hero
        badge_platform: "安哥拉第一平台",
        hero_title_1: "在安哥拉销售，",
        hero_title_2: "征服世界。",
        hero_desc: "将您的产品带出国门的完整解决方案。安全支付，综合物流。",
        btn_buy: "开始购物",
        btn_become_vendor: "成为卖家",
        feature_secure_payments: "安全支付",
        feature_intl_shipping: "国际航运",
        feature_vendor_count: "+1000 卖家",

        // Categories
        cat_title: "按类别浏览",
        cat_desc: "在我们的主要类别中找到您想要的东西。",
        cat_electronics: "电子产品",
        cat_fashion: "时尚",
        cat_home: "家居装饰",
        cat_beauty: "美容",
        cat_sports: "运动",
        cat_toys: "玩具",
        cat_books: "书籍",
        cat_food: "食品",
        cat_others: "其他",

        // ID Aliases
        cat_eletronicos: "电子产品",
        cat_moda: "时尚",
        cat_beleza: "美容",
        cat_desporto: "运动",
        cat_alimentos: "食品",
        cat_outros: "其他",
        cat_subtitle: "在我们的主要类别中找到您想要的东西。",
        cat_view_all: "查看全部",

        // Trust Signals
        trust_delivery_title: "送货上门",
        trust_delivery_desc: "全国配送",
        trust_secure_title: "安全购物",
        trust_secure_desc: "数据受保护",
        trust_payment_title: "支付方式",
        trust_payment_desc: "Multicaixa,转账",
        trust_discount_title: "5% 折扣",
        trust_discount_desc: "现金支付",

        // Value Props
        prop_global_title: "全球覆盖",
        prop_global_desc: "不要限制自己。我们的平台将您的产品推向全球客户。",
        prop_security_title: "安全保证",
        prop_security_desc: "受保护的交易和卖家验证，确保每次购买的信任。",
        prop_growth_title: "快速增长",
        prop_growth_desc: "分析和管理工具帮助您的业务扩展。",

        // CTA
        cta_title: "准备开始了吗？",
        cta_desc: "加入成千上万已经使用 ProCommerceGlobal 改变业务的企业家。",
        cta_btn: "创建免费账户",

        // Cart
        cart_title: "您的购物车",
        cart_empty: "您的购物车是空的。",
        cart_continue: "继续购物",
        cart_subtotal: "小计",
        cart_delivery_fee: "运费",
        cart_total: "总计",
        cart_checkout: "结账",
        cart_delivery_method: "配送方式",
        cart_delivery: "配送",
        cart_pickup: "自提",
        cart_remove: "移除",
        cart_free: "免费",

        // Footer
        footer_slogan: "安哥拉领先的电子商务平台。",
        footer_platform: "平台",
        footer_company: "公司",
        footer_legal: "法律",
        footer_about: "关于我们",
        footer_careers: "职业",
        footer_contact: "联系方式",
        footer_terms: "使用条款",
        footer_privacy: "隐私",
        footer_copyright: "ProCommerceGlobal. 在安哥拉用 ❤️ 制作。",

        // Featured
        featured_title: "本周精选",
        featured_desc: "精选优质产品，最优惠的价格。",
        btn_view_details: "查看详情",

        // Common Actions & Labels
        common_save: "保存",
        common_cancel: "取消",
        common_edit: "编辑",
        common_delete: "删除",
        common_search: "搜索",
        common_filter: "筛选",
        common_back: "返回",
        common_next: "下一步",
        common_loading: "加载中...",
        common_success: "成功！",
        common_error: "错误",
        common_actions: "操作",
        common_status: "状态",
        common_date: "日期",
        common_all: "全部",

        // Auth
        auth_email: "电子邮件地址",
        auth_password: "密码",
        auth_name: "全名",
        auth_login_title: "欢迎回来",
        auth_register_title: "创建您的帐户",
        auth_login_desc: "输入您的电子邮件和密码访问您的帐户。",
        auth_register_desc: "填写以下详细信息开始使用平台。",
        auth_forgot_password: "忘记密码？",
        auth_have_account: "已经有帐户？登录",
        auth_no_account: "没有帐户？注册",
        auth_or: "或",
        auth_term_customer: "创建客户帐户",
        auth_term_vendor: "成为卖家",
        auth_desc_customer: "加入成千上万的购物者。",
        auth_desc_vendor: "今天就开始向数百万客户销售您的产品。",
        auth_role_customer: "我是购物者",
        auth_role_vendor: "我是卖家",
        auth_vendor_data_title: "业务/卖家数据",
        auth_vendor_data_desc: "我们需要一些详细信息来验证您的企业帐户。",
        auth_doc_copy: "文件副本",
        auth_doc_hint: "上传清晰的照片或 PDF。",
        auth_error_required: "请填写所有必填字段。",
        auth_error_password_match: "密码不匹配。",
        auth_error_password_length: "密码必须至少为 6 个字符。",

        // Products
        prod_add_to_cart: "加入购物车",
        prod_buy_now: "立即购买",
        prod_description: "描述",
        prod_specifications: "规格",
        prod_reviews: "评论",
        prod_stock: "有货",
        prod_out_stock: "缺货",
        prod_sku: "SKU",
        prod_category: "类别",
        prod_related: "相关产品",
        prod_from_price: "起价",
        prod_check_offer: "查看优惠",
        prod_no_featured: "目前没有精选产品。",
        prod_no_highlight: "目前没有重点产品。",
        prod_sold_by: "销售商：",
        prod_units: "单位",
        prod_unavailable: "不可用",
        prod_secure_transaction: "ProCommerceGlobal 保证交易安全",
        prod_default_category: "常规",

        // Marketplace
        marketplace_title: "ProCommerceGlobal 市场",
        marketplace_subtitle: "发现安哥拉企业家的惊人产品",
        marketplace_all_products: "所有产品",
        marketplace_no_products: "未找到产品",
        marketplace_no_products_desc: "尝试选择其他类别或稍后回来查看。",
        // Cart & Checkout
        cart_empty_title: "您的购物车是空的",
        cart_empty_desc: "看看我们的产品怎么样？",
        cart_view_products: "查看产品",
        cart_summary: "订单摘要",
        cart_clear: "清空购物车",

        // Common
        common_back_store: "返回商店",
        footer_rights: "保留所有权利。",
        // Reviews
        reviews_title: "客户评论",
        reviews_loading: "正在加载评论...",
        reviews_empty: "该产品暂无评论。",
        reviews_be_first: "成为第一个评价的人！",
        reviews_client: "客户",
        reviews_write: "写评论",
        reviews_rating: "您的评分",
        reviews_comment: "您的评论",
        reviews_placeholder: "告诉我们您的想法...",
        reviews_submit: "提交评论",
        reviews_submitting: "提交中...",
        reviews_login_req: "您需要登录才能评价此产品。",
        reviews_login_btn: "登录",
        reviews_success: "评论提交成功！",

        // Tracking
        track_title: "追踪订单",
        track_desc: "输入追踪码查看状态。",
        track_label: "追踪码",
        track_btn: "立即追踪",
        track_searching: "搜索中...",
        track_current_status: "当前状态",
        track_via: "通过",
        track_destination: "目的地",
        track_forecast: "预计",
        track_days: "天",
        track_history: "事件历史",
        track_waiting: "等待更新...",
        track_not_found: "未找到订单",
        track_error: "搜索错误",

        // Register
        reg_title: "创建新账户",
        reg_choose_role: "选择您的角色：",
        reg_customer: "客户",
        reg_vendor: "卖家",
        reg_continue: "继续注册",
        reg_origin_title: "卖家来源",
        reg_origin_national: "国内",
        reg_origin_intl: "国际",
        reg_doc_accepted: "接受的证件",
        reg_doc_accepted_plural: "接受的证件",
        reg_data_account: "账户详情",
        reg_data_personal: "个人数据和证件",
        reg_data_business: "企业 / 店铺数据",
        reg_personal_phone: "个人电话",
        reg_birth_date: "出生日期",
        reg_address_personal: "家庭地址",
        reg_doc_type: "证件类型",
        reg_doc_number: "证件号码",
        reg_upload_title: "上传",
        reg_doc_front_only: "护照仅需发送个人信息页（正面）。",
        reg_doc_both_sides: "此证件需要正反两面。",
        reg_magic_title: "使用手机上传照片",
        reg_magic_desc: "用手机相机扫描上方二维码。",
        reg_magic_connected: "已连接",
        reg_magic_new_code: "生成新代码",
        reg_success_photos: "照片接收成功！",
        reg_front: "正面",
        reg_back_side: "背面",
        reg_store_name: "店铺名称",
        reg_nif: "税务识别号",
        reg_email_biz: "商务邮箱",
        reg_phone_biz: "商务电话",
        reg_address_biz: "总部地址",
        reg_country_biz: "国际总部国家",
        reg_btn_back: "返回",
        reg_btn_finish: "完成注册",
        reg_creating: "正在创建账户...",

        // Checkout Expanded
        checkout_coupon_title: "有优惠券吗？",
        checkout_coupon_placeholder: "优惠券代码",
        checkout_coupon_apply: "应用",
        checkout_coupon_validating: "验证中...",
        checkout_coupon_success: "优惠券已应用！",
        checkout_coupon_invalid: "无效优惠券",
        checkout_negotiable: "面议",
        checkout_method_select: "选择方式",
        checkout_payment_select: "选择支付",
        checkout_personal_data: "您的数据",
    }
}

const FLAGS: Record<Language, string> = {
    PT: "https://flagcdn.com/w40/ao.png", // Angola as primary PT
    EN: "https://flagcdn.com/w40/us.png",
    FR: "https://flagcdn.com/w40/fr.png",
    ES: "https://flagcdn.com/w40/es.png",
    CN: "https://flagcdn.com/w40/cn.png",
    RU: "https://flagcdn.com/w40/ru.png"
}

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("PT")

    // Optional: Load from localStorage on mount
    useEffect(() => {
        const savedLang = localStorage.getItem("app_language") as Language
        if (savedLang && translations[savedLang]) {
            setLanguage(savedLang)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        localStorage.setItem("app_language", lang)
    }

    const getFlag = (lang: Language) => FLAGS[lang]

    const t = (key: string) => {
        // @ts-ignore
        return translations[language][key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, flags: FLAGS, getFlag }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
